version: '3.2'
services:
  app:
    container_name: express-basic
    restart: on-failure
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
